/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan
{
	unsafe public partial class MirSurfaceCreateInfoKhr
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public MirConnection Connection {
			get { return m->Connection; }
			set { m->Connection = value; }
		}

		public MirSurface MirSurface {
			get { return m->MirSurface; }
			set { m->MirSurface = value; }
		}
		internal Linux.Interop.MirSurfaceCreateInfoKhr* m;

		public MirSurfaceCreateInfoKhr ()
		{
			m = (Linux.Interop.MirSurfaceCreateInfoKhr*) Interop.Structure.Allocate (typeof (Linux.Interop.MirSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal MirSurfaceCreateInfoKhr (Linux.Interop.MirSurfaceCreateInfoKhr* ptr)
		{
			m = ptr;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.MirSurfaceCreateInfoKhr;
		}

	}

	unsafe public partial class WaylandSurfaceCreateInfoKhr
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public wl_display Display {
			get { return m->Display; }
			set { m->Display = value; }
		}

		public wl_surface Surface {
			get { return m->Surface; }
			set { m->Surface = value; }
		}
		internal Linux.Interop.WaylandSurfaceCreateInfoKhr* m;

		public WaylandSurfaceCreateInfoKhr ()
		{
			m = (Linux.Interop.WaylandSurfaceCreateInfoKhr*) Interop.Structure.Allocate (typeof (Linux.Interop.WaylandSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal WaylandSurfaceCreateInfoKhr (Linux.Interop.WaylandSurfaceCreateInfoKhr* ptr)
		{
			m = ptr;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.WaylandSurfaceCreateInfoKhr;
		}

	}

	unsafe public partial class XlibSurfaceCreateInfoKhr
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public Display Dpy {
			get { return m->Dpy; }
			set { m->Dpy = value; }
		}

		public Window Window {
			get { return m->Window; }
			set { m->Window = value; }
		}
		internal Linux.Interop.XlibSurfaceCreateInfoKhr* m;

		public XlibSurfaceCreateInfoKhr ()
		{
			m = (Linux.Interop.XlibSurfaceCreateInfoKhr*) Interop.Structure.Allocate (typeof (Linux.Interop.XlibSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal XlibSurfaceCreateInfoKhr (Linux.Interop.XlibSurfaceCreateInfoKhr* ptr)
		{
			m = ptr;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.XlibSurfaceCreateInfoKhr;
		}

	}

	unsafe public partial class XcbSurfaceCreateInfoKhr
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public IntPtr Connection {
			get { return m->Connection; }
			set { m->Connection = value; }
		}

		public IntPtr Window {
			get { return m->Window; }
			set { m->Window = value; }
		}
		internal Linux.Interop.XcbSurfaceCreateInfoKhr* m;

		public XcbSurfaceCreateInfoKhr ()
		{
			m = (Linux.Interop.XcbSurfaceCreateInfoKhr*) Interop.Structure.Allocate (typeof (Linux.Interop.XcbSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal XcbSurfaceCreateInfoKhr (Linux.Interop.XcbSurfaceCreateInfoKhr* ptr)
		{
			m = ptr;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.XcbSurfaceCreateInfoKhr;
		}

	}

}
